#+TITLE: Puzzles
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty

No help from me! Or brother Neff! Or any professor!
Other rando's ... sure.  Other students ... even bettar!

To get full "extra credit" you must fill out all four. 
Solutions and proofs are different.  Solving a puzzle like the bomb puzzle in a previous lab
is much different than proving it is impossible if we don't know if the bomb is heavier or lighter
with only 2 weights!

* Puzzles
** DONE TEU
  How many numbers between one and a million contain the digit 1 exactly once,
  and the sum of the rest of the digits is 16? Write elisp code with and without
  loops to verify your answer.
*** Rephrase

 What is the number of 6-diget sequences that sum to 17 and have exactly one "1".

*** Approach

 I first created a program in Ruby to find the answer, then converted it to elisp.
 Looking for a better solution, I rememberd that the sum of the digets of a natral number is 
 always equivalent to the number mod 9. This means that I only need to check numbers equivalent
 to 17 mod 9. This cuts 88% off runtime, but has little .

*** Solution

 9150

*** Proof

This is the code with loops. Interestingly, the ruby code it came from could be said to have
"no loops," but I could not get =count= or =valid= working without loops, and so I gave up.

#+BEGIN_SRC emacs-lisp
(defun count (f l) ; how many items in a list hava a given property?
  (let ((c 0))
    (dolist (x l)
      (if (apply f (list x)) (setq c (+ 1 c)))
    )
    c
  )
)

(defun valid (n) ; check if a number has one "1" and the digets sum to 17. 
  (let (
      (str (number-to-string n))
      (i 0)
      (sum 0)
      (ones 0))
    (while (< i (length str))
      (setq sum (+ sum (- (aref str i) ?0)))
      (if (= (aref str i) ?1)
        (setq ones (+ ones 1))
      )
      (setq i (+ i 1))
    )
    (and (= ones 1) (= sum 17))
  )
)


 ; The jump size of 9 is an optimization: any number with digets summing to 17 must
 ;  be one less than a mutiple of 9. 
(princ (count 'valid (number-sequence 8 1000000 9)))
#+END_SRC

** TODO TME
  Sequences can be non-numeric as well. What is the pattern for this sequence?
: [m b w y me be wi yo met bew ith you meta bewi thyo uati metap bewit hyoua tirel]
  How long can it continue?
*** Rephrase
*** Approach
*** Solution
*** Proof

** DONE WRA
  Why is the sum of the reciprocals of the powers of two scaled by which power
  equal to two?
*** Rephrase

The infinite sum 1/2+1/4+1/8+1/16... mutiplied by 2^n is equal to 2 for which n? Why is this the case?

*** Approach

I use my basic knowledge of geometric series to see that the sum is equal to 1. 

*** Solution

The power we are looking for is 2 = 2^1.
As for why, see the proof below.

*** Proof

let X = (1/2 + 1/4 + 1/8 + 1/16...)
X * 2 = 1 + 1/2 + 1/4 + 1/8... = 1 + X
2X = 1+X
X=1

Thus X * 2^1 = 2
